Branch levels
dusk-network/microkelvin pull request #45
Opened 2021-04-19 10:51 UTC by krl

Expose the `levels` of a Branch for inspection.

2021-04-19 11:14 UTC, krl commented
fixes #46

2021-04-20 15:14 UTC, ZER0 requested changes
LGTM, with the comments fixed.

2021-04-20 15:14 UTC, ZER0 commented on src/walk.rs
> +/// annotation
I believe the comments are copied from the nth, this should said `a first() method`, is that correct?

2021-04-20 15:14 UTC, ZER0 commented on src/walk.rs
> +    /// Construct a `Branch` pointing to the `nth` element, if any
here as well

2021-04-20 15:14 UTC, ZER0 commented on src/walk.rs
> +    /// Construct a `BranchMut` pointing to the `nth` element, if any
And probably here too.

2021-04-20 15:31 UTC, ZER0 approved these changes

2021-04-20 15:35 UTC, merged