Release 0.8.0
dusk-network/microkelvin pull request #55
Opened 2021-06-18 10:56 UTC by krl

2021-06-18 10:57 UTC, krl commented
fixes #53

2021-06-18 14:07 UTC, krl commented
fixes #44

2021-06-21 07:28 UTC, ZER0 requested changes
LGTM. Please fix the leftover in the changelog, and possibly add at the end of the commits (and this PR description) "Resolves: #xx" where "#xx" is the issue they're solving.

2021-06-21 07:28 UTC, ZER0 commented on CHANGELOG.md
> +=======
Leftover, please remove.

2021-06-21 16:12 UTC, ZER0 approved these changes

2021-06-21 16:17 UTC, merged