Implement mmap file backing for hoststore
dusk-network/microkelvin pull request #90
Opened 2021-12-10 15:51 UTC by miloszm

mmap file backing for hoststore, includes a fix in Storage::get for ofs%PAGE_SIZE==0

2021-12-10 19:02 UTC, krl requested changes

2021-12-14 10:16 UTC, miloszm commented on src/storage/host_store.rs
> +        if ofs == 0 {
corrected to check if offset is greater or equal to stored data size, if stored size it zero, there will be no panic

2021-12-14 10:50 UTC, krl requested changes

2021-12-14 10:50 UTC, krl commented on src/storage/mod.rs
> +
I don't think it makes sense to have the persist as part of the trait, it should be directly on the HostStore. Not all stores will be supporting persistance.

2021-12-14 14:24 UTC, krl approved these changes

2021-12-14 14:32 UTC, merged